{
 "title": "MTM - Locations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   { "name": "fc_data_rate", "query": "0.85" },
   {
    "name": "location",
    "label": "Location",
    "query": "show tag values from \"$db\".\"$rp\".\"Switches\" with key=location where $timeFilter"
   },
   { "name": "min_interval", "query": "10" },
   {
    "name": "num_locations",
    "query": " SHOW TAG VALUES CARDINALITY FROM \"$db\".\"$rp\".\"Switches\" WITH KEY=location"
   },
   {
    "name": "num_switches",
    "query": " SHOW TAG VALUES CARDINALITY FROM \"$db\".\"$rp\".\"Switches\" WITH KEY=switch"
   },
   { "name": "min_interval_sum", "query": "300" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>MTM - MDS Traffic Monitoring - Locations (<span style=\"color: #ff00ff;\">$location</span>)</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "# Total Locations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"switchname\") FROM \"$db\".\"$rp\".\"Switches\" WHERE $timeFilter GROUP BY time($__interval),location) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Switches in $location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"switchname\") FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"location\" =~ /^$location$/) and $timeFilter GROUP BY time($__interval),switch) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Up\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' and oper_state != 'down') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Down\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' and oper_state = 'down') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch ports",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT description as \"Description\", oper_state as \"Operational State\", oper_mode as \"Oper Mode\", oper_speed as \"Speed (G)\", pc as \"Member of Port-Channel\", pwwn as \"PWWN\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/) AND  $timeFilter GROUP BY switch,switchport order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# FC Ports in $location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# FC Port-Channel in $location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" = '') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port Speeds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"32G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 32) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 16) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 8) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"10G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 4) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"2G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' AND \"oper_speed\" = 2) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Polling Response Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_switch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"response_time\" as \"Response Time\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"location\" =~ /^$location$/) and $timeFilter GROUP BY switch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port mode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"TF\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' and oper_mode = 'TF') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"F\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' and oper_mode = 'F') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"TE\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ AND \"pc\" != '' and oper_mode = 'TE') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switches",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT switchname as \"Switch Name\", sys_uptime as \"Systerm Uptime\", kernel_uptime as \"Kernel Uptime\", chassis_id as \"Switch type\", cpu_kernel as \"CPU Util - Kernel\", cpu_user as \"CPU Util - User\", (\"mem_used\")/(\"mem_total\")*100 as \"Memory Util\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"location\" =~ /^$location$/) AND  $timeFilter GROUP BY switch,location order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switchport Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"RX Traffic\") as \"Total RX Traffic\" from (SELECT non_negative_difference(mean(rx_bytes))*8/elapsed(mean(oper_speed),1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ and pc != '' and oper_state != 'down') AND $timeFilter GROUP BY time([[__interval]]),switch,switchport) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"TX Traffic\") as \"Total TX Traffic\" from (SELECT non_negative_difference(mean(tx_bytes))*8/elapsed(mean(oper_speed),1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"location\" =~ /^$location$/ and pc != '' and oper_state != 'down') AND $timeFilter GROUP BY time([[__interval]]),switch,switchport) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TxWait\" from (SELECT non_negative_difference(mean(txwait))*2.5/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switchport,switch,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Tx B2B Transition to 0\" from (SELECT non_negative_difference(mean(tx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Rx B2B Transition to 0\" from (SELECT non_negative_difference(mean(rx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switchport,switch,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total CRC\" from (SELECT non_negative_difference(mean(crc))/elapsed(mean(oper_speed),1s)  FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Utilized Ports - RX",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"percent_util\",switchport,switch,10) as \"RX % Utilization\" from (SELECT ((non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed)*1000000000*[[fc_data_rate]]))*100  as \"percent_util\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Utilized Ports  - TX",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"percent_util\",switchport,switch,10) as \"TX % Utilization\" from (SELECT ((non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed)*1000000000*[[fc_data_rate]]))*100  as \"percent_util\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Congested Ports - TxWait",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"TxWait\" from (SELECT non_negative_difference(mean(txwait))*2.5/(elapsed(mean(oper_speed),1s) * 1000000) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - TX B2B to 0",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Tx B2B Transition to 0\" from (SELECT non_negative_difference(mean(tx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - TX B2B to 0",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Rx B2B Transition to 0\" from (SELECT non_negative_difference(mean(rx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switchport,switch,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - CRC",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"CRC\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Timeout Discard\" from (SELECT non_negative_difference(mean(timeout_discards))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Rx Discard\" from (SELECT non_negative_difference(mean(rx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Tx Discard\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total FEC Corrected\" from (SELECT non_negative_difference(mean(fec_corrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total FEC Uncorrected\" from (SELECT non_negative_difference(mean(fec_uncorrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total ITW\" from (SELECT non_negative_difference(mean(itw))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - Timeout Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Timeout Discards\" from (SELECT non_negative_difference(mean(timeout_discards))/(elapsed(mean(oper_speed),1s)) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - RX Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Rx Discard\" from (SELECT non_negative_difference(mean(rx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - TX Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"TX Discard\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - FEC Corrected",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"FEC Corrected\" from (SELECT non_negative_difference(mean(fec_corrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - FEC Uncorrected",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"FEC Uncorrected\" from (SELECT non_negative_difference(mean(fec_uncorrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - ITW",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Invalid Transmission Words\" from (SELECT non_negative_difference(mean(itw))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Link Failure\" from (SELECT non_negative_difference(mean(link_failures))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Signal Loss\" from (SELECT non_negative_difference(mean(signal_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Sync Loss\" from (SELECT non_negative_difference(mean(sync_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total RX LR\" from (SELECT non_negative_difference(mean(rx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TX LR\" from (SELECT non_negative_difference(mean(tx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total RX LRR\" from (SELECT non_negative_difference(mean(rx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TX LRR\" from (SELECT non_negative_difference(mean(tx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - Link Failure",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Link Failure\" from (SELECT non_negative_difference(mean(link_failures))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - Signal Loss",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Signal Loss\" from (SELECT non_negative_difference(mean(signal_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - Sync Loss",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"Sync Loss\" from (SELECT non_negative_difference(mean(sync_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - RX Link Reset",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 12, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"RX LR\" from (SELECT non_negative_difference(mean(rx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - TX Link Reset",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 15, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"TX LR\" from (SELECT non_negative_difference(mean(tx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - RX Link Reset Response",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 18, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"RX LRR\" from (SELECT non_negative_difference(mean(rx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 Ports - TX Link Reset Response",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 21, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"non_negative_difference_elapsed\",switch,switchport,10) as \"TX LRR\" from (SELECT non_negative_difference(mean(tx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"location\" =~ /^$location$/ AND $timeFilter GROUP BY switch,switchport,time($__interval)) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}