{
 "title": "MTM - MDS Switch Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "${VAR_DB}" },
   { "name": "rp", "label": "Retention Policy", "query": "${VAR_RP}" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   { "name": "fc_data_rate", "query": "${VAR_FC_DATA_RATE}" },
   {
    "name": "switch",
    "label": "Switch",
    "query": "show tag values from  \"$db\".\"$rp\".\"Switches\" with key=switch  WHERE $timeFilter "
   },
   { "name": "min_interval_sum", "query": "${VAR_MIN_INTERVAL_SUM}" },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(switchname,1s) from \"$db\".\"$rp\".\"Switches\" where switch =~ /$switch/)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>MTM - MDS Traffic Monitoring</strong></span></h2>\n<h5 style=\"text-align: center; margin: 0px;\"><span style=\"color: #ff00ff;\">Detailed Switch Monitoring</span></span></h5>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"switchname\"),location FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"switchname\") as \"Switchname\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select switch as \"Switch Address\" from (SELECT last(\"switchname\"),switch  FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"chassis_id\") FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "NX-OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"sys_ver\") FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "# FC Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '') and $timeFilter GROUP BY switch,switchport) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# FC Port-Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" = '') and $timeFilter GROUP BY switch,switchport) where $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Kernel - % CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_kernel\") as \"Kernel - % CPU\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User - % CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_user\") as \"User - % CPU\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"load_avg_1min\") as \"Load\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "load_avg_1min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT last(\"mem_used\")/last(\"mem_total\")*100 FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switch Port Inventory",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT description as \"Description\", oper_state as \"Operational State\", port_down_reason as \"Down Reason\", oper_mode as \"Oper Mode\", oper_speed as \"Speed (G)\", pc as \"Member of Port-Channel\", pwwn as \"PWWN\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/) AND  $timeFilter GROUP BY switch,switchport order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(\"cpu_user\") AS \"CPU User\", mean(\"cpu_kernel\") AS \"CPU Kernel\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU User" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_kernel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU Kernel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT (mean(mem_used)/mean(mem_total)) as \"Mem Used %\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kernel Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"kernel_uptime\") AS \"Uptime\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "NXAPI Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switches",
     "query": "SELECT mean(response_time) as \"Response Time\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"sys_uptime\") AS \"Uptime\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Sup Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"active_sup_uptime\") AS \"Active Sup Uptime\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "FC Port State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Up\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' and oper_state != 'down') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Down\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' and oper_state = 'down') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port Down Reason",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Admin Down\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"port_down_reason\" = 'Administratively down') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Link failure or not-connected\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"port_down_reason\" = 'Link failure or not-connected') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"SFP not present\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"port_down_reason\" = 'SFP not present') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"Error disabled\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"port_down_reason\" =~ /Error disabled/) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"32G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 32) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 16) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 8) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"10G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 4) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"2G\" from (SELECT last(\"oper_speed\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' AND \"oper_speed\" = 2) and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FC Port Mode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"TF\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' and oper_mode = 'TF') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"F\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' and oper_mode = 'F') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) AS \"TE\" from (SELECT last(\"crc\") FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" != '' and oper_mode = 'TE') and $timeFilter GROUP BY time($__interval),switch,switchport) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Switchport Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"RX Traffic\") as \"Total RX Traffic\" from (SELECT non_negative_difference(mean(rx_bytes))*8/elapsed(mean(oper_speed),1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ and pc != '' and oper_state != 'down') AND $timeFilter GROUP BY time([[__interval]]),switchport) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"TX Traffic\") as \"Total TX Traffic\" from (SELECT non_negative_difference(mean(tx_bytes))*8/elapsed(mean(oper_speed),1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ and pc != '' and oper_state != 'down') AND $timeFilter GROUP BY time([[__interval]]),switchport) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TxWait\" from (SELECT non_negative_difference(mean(txwait))*2.5/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Tx B2B Transition to 0\" from (SELECT non_negative_difference(mean(tx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Rx B2B Transition to 0\" from (SELECT non_negative_difference(mean(rx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter group by time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total CRC\" from (SELECT non_negative_difference(mean(crc))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Port Utilization - RX",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(non_negative_difference_elapsed_mean)  as \"RX % Utilization\" from (SELECT ((non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed)*1000000000*[[fc_data_rate]]))*100  FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Port Utilization - TX",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(non_negative_difference_elapsed_mean)  as \"TX % Utilization\" from (SELECT ((non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed)*1000000000*[[fc_data_rate]]))*100  FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Port Congestion - TxWait",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"TxWait\" from (SELECT (non_negative_difference(mean(txwait))*2.5)/(elapsed(mean(oper_speed),1s)*1000000) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter group by switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Port Congestion - TX B2B to 0",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(non_negative_difference_elapsed) as \"Tx B2B Transition to 0\" from (SELECT non_negative_difference(mean(tx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Port Congestion - RX B2B to 0",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(non_negative_difference_elapsed) as \"Rx B2B Transition to 0\" from (SELECT non_negative_difference(mean(rx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CRC",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"CRC\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval) fill(null)) where $timeFilter group by switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hottest SFPs",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select top(\"last\",switchport,10) as \"SFP Temperature\" from (SELECT last(sfp_temperature) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Coldest SFPs",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select bottom(\"last\",switchport,10) as \"SFP Temperature\" from (SELECT last(sfp_temperature) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Lowest SFP RX Power",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select bottom(\"last\",switchport,10) as \"SFP Rx Power\" from (SELECT last(sfp_rx_pwr) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and oper_state != 'down' and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Lowest SFP TX Power",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select bottom(\"last\",switchport,10) as \"SFP Tx Power\" from (SELECT last(sfp_tx_pwr) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and oper_state != 'down' and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport) where $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Timeout Discard\" from (SELECT non_negative_difference(mean(timeout_discards))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Rx Discard\" from (SELECT non_negative_difference(mean(rx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Tx Discard\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total FEC Corrected\" from (SELECT non_negative_difference(mean(fec_corrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval) fill(linear)) where $timeFilter GROUP BY time([[__interval_ms]]ms)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total FEC Uncorrected\" from (SELECT non_negative_difference(mean(fec_uncorrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total ITW\" from (SELECT non_negative_difference(mean(itw))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval) fill(linear)) where $timeFilter GROUP BY time([[__interval_ms]]ms)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Timeout Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Timeout Discards\" from (SELECT non_negative_difference(mean(timeout_discards))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RX Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Rx Discard\" from (SELECT non_negative_difference(mean(rx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TX Discard",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"TX Discard\" from (SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FEC Corrected",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"FEC Corrected\" from (SELECT non_negative_difference(mean(fec_corrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FEC Uncorrected",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"FEC Uncorrected\" from (SELECT non_negative_difference(mean(fec_uncorrected))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": " ITW",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Invalid Transmission Words\" from (SELECT non_negative_difference(mean(itw))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Link Failure\" from (SELECT non_negative_difference(mean(link_failures))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Signal Loss\" from (SELECT non_negative_difference(mean(signal_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total Sync Loss\" from (SELECT non_negative_difference(mean(sync_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total RX LR\" from (SELECT non_negative_difference(mean(rx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TX LR\" from (SELECT non_negative_difference(mean(tx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total RX LRR\" from (SELECT non_negative_difference(mean(rx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"non_negative_difference_elapsed\") as \"Total TX LRR\" from (SELECT non_negative_difference(mean(tx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY time([[__interval]])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": " Link Failure",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Link Failure\" from (SELECT non_negative_difference(mean(link_failures))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Signal Loss",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Signal Loss\" from (SELECT non_negative_difference(mean(signal_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sync Loss",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 8, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"Sync Loss\" from (SELECT non_negative_difference(mean(sync_loss))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RX Link Reset",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 12, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"RX LR\" from (SELECT non_negative_difference(mean(rx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TX Link Reset",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 15, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"TX LR\" from (SELECT non_negative_difference(mean(tx_lr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RX Link Reset Response",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 18, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"RX LRR\" from (SELECT non_negative_difference(mean(rx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TX Link Reset Response",
     "type": "table",
     "gridPos": { "h": 12, "w": 3, "x": 21, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"non_negative_difference_elapsed\") as \"TX LRR\" from (SELECT non_negative_difference(mean(tx_lrr))/elapsed(mean(oper_speed),1s) FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE \"pc\" != '' and \"oper_state\" != 'down'  and \"switch\" =~ /^$switch$/ AND $timeFilter GROUP BY switchport,time($__interval)) where $timeFilter GROUP BY switchport",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}