{
 "title": "MTM - MDS Switchports",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   { "name": "fc_data_rate", "query": "0.85" },
   {
    "name": "switch",
    "label": "Switch",
    "query": "show tag values from  \"$db\".\"$rp\".\"Switches\" with key=switch  WHERE $timeFilter "
   },
   {
    "name": "switchport",
    "label": "Switch Port",
    "query": "show tag values from \"$db\".\"$rp\".\"SwitchPortStats\" with key=switchport where switch =~ /$switch/ and $timeFilter"
   },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(switchname,1s) from \"$db\".\"$rp\".\"Switches\" where switch =~ /$switch/ and $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>MTM - MDS Traffic Monitoring - Switchports</strong></span></h2>\n<h5 style=\"text-align: center; margin: 0px;\"><span style=\"color: #ff00ff;\">Detailed Switchport Monitoring</span></span></h5>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/mtm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   }
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT location as Location, description as \"Description\", oper_state as \"Operational State\", oper_mode as \"Oper Mode\", oper_speed as \"Speed (G)\", pc as \"Member of Port-Channel\", pwwn as \"PWWN\", vsan as \"VSAN\", last_changed as \"Last status changed at\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ and \"switchport\" =~ /^$switchport$/) AND  $timeFilter GROUP BY switch,switchport order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT switchname as \"Switch Name\" FROM \"$db\".\"$rp\".\"Switches\" WHERE (\"switch\" =~ /^$switch$/) AND  $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Traffic and Congestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Traffic on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT (non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"RX Traffic\",(non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "% Utilization on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT (non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed)*1000000000*[[fc_data_rate]]) as \"RX Traffic\", (non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8/(mean(oper_speed) * 1000000000*[[fc_data_rate]]) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    },
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(oper_speed) as \"Max\" from \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Congestion on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT non_negative_difference(mean(txwait))*2.5/(elapsed(mean(oper_speed),1s)*1000000) as \"TxWait\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "B2B transition to 0 on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT non_negative_difference(mean(rx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) as \"RX B2B transition to 0\",non_negative_difference(mean(tx_b2b_credit_to_zero))/elapsed(mean(oper_speed),1s) as \"TX B2B transition to 0\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Credit Loss on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT non_negative_difference(mean(credit_loss))/elapsed(mean(oper_speed),1s) as \"Credit Loss\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "B2B remaining credit on $switchport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_switchport",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "SwitchPortStats",
     "query": "SELECT mean(rx_b2b_credit_remain) as \"RX B2B remaining\",mean(tx_b2b_credit_remain) as \"TX B2B remaining\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT non_negative_difference(mean(tx_discard))/elapsed(mean(oper_speed),1s) as \"TX Discards\", non_negative_difference(mean(rx_discard))/elapsed(mean(oper_speed),1s) as \"RX Discards\",non_negative_difference(mean(timeout_discards))/elapsed(mean(oper_speed),1s) as \"Timeout Discards\",non_negative_difference(mean(crc))/elapsed(mean(oper_speed),1s) as \"CRC\",non_negative_difference(mean(fec_corrected))/elapsed(mean(oper_speed),1s) as \"FEC Corrected\",non_negative_difference(mean(fec_uncorrected))/elapsed(mean(oper_speed),1s) as \"FEC Uncorrected\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT non_negative_difference(mean(itw))/elapsed(mean(oper_speed),1s) as \"ITW\",non_negative_difference(mean(link_failures))/elapsed(mean(oper_speed),1s) as \"Link Failure\",non_negative_difference(mean(rx_lr))/elapsed(mean(oper_speed),1s) as \"RX LR\",non_negative_difference(mean(tx_lr))/elapsed(mean(oper_speed),1s) as \"TX LR\",non_negative_difference(mean(rx_lrr))/elapsed(mean(oper_speed),1s) as \"RX LRR\" ,non_negative_difference(mean(tx_lrr))/elapsed(mean(oper_speed),1s) as \"TX LRR\" ,non_negative_difference(mean(signal_loss))/elapsed(mean(oper_speed),1s) as \"Signal Loss\",non_negative_difference(mean(sync_loss))/elapsed(mean(oper_speed),1s) as \"Sync Loss\"   FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Digital Optical Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT mean(sfp_current) as \"SFP Current\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    },
    {
     "title": "Voltage on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT mean(sfp_voltage) as \"SFP Voltage\"  FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    },
    {
     "title": "Temperature on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT mean(sfp_temperature) as \"SFP Temperature\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    },
    {
     "title": "Power on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT mean(sfp_tx_pwr) as \"SFP TX PWR\", mean(sfp_rx_pwr) as \"SFP RX PWR\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel traffic distribution (Must Select a port-channel interface from Switch Port menu)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Traffic distribution on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT (non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      },
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT (non_negative_difference(mean(rx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"RX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]*20),switch,switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic distribution on $switchport",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT (non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"switchport\" =~ /^$switchport$/) AND $timeFilter GROUP BY time($__interval),switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      },
      {
       "alias": "$col $tag_switchport",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "SwitchPortStats",
       "query": "SELECT (non_negative_difference(mean(tx_bytes))/elapsed(mean(oper_speed),1s))*8 as \"TX Traffic\" FROM \"$db\".\"$rp\".\"SwitchPortStats\" WHERE (\"switch\" =~ /^$switch$/ AND \"pc\" =~ /^$switchport$/) AND $timeFilter GROUP BY time([[__interval]]*20),switch,switchport fill(null)",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "switch", "operator": "=~", "value": "/^$switch$/" },
        { "condition": "AND", "key": "switchport", "operator": "=~", "value": "/^$switchport$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}